### ISSUE TITLE
Cannot Registration

### ISSUE THREAD

**Issue by nian88** [barokurniawan/wabot-service#7]
Cannot next step in registration form..

**Comment by barokurniawan** [comment]
can you mention what environment you are using, PHP Version, Node Js Version, are you using docker?
And please describe how to reproduce the error please.

**Comment by nian88** [comment]
![image](https://user-images.githubusercontent.com/18239536/93470809-ab814e00-f91c-11ea-8d27-aaaec54097de.png)

![image](https://user-images.githubusercontent.com/18239536/93470891-ceabfd80-f91c-11ea-8091-11a7c52f408c.png)


Number registered but tab QR not show

**Comment by barokurniawan** [comment]
I have made some changes in the master, hopefully that will solve your issue.
All you have to do is pull the master branch, then rebuild it.

then run `composer update` in the wabout_gui container and run `npm install` in the wabot_engine container.

If you get stucked in registration after entring the phone number, then reload the page and do the registration again, you will be prompted an alert then just click OK then you will see the QRCode.

Hope it solve your issue.

**Comment by barokurniawan** [comment]
And add `ENGINE_URL = "http://wabot_engine:3002"` to your .env file.
